### ISSUE TITLE
How do we define a contract in serving.yaml for a function call - fn(....)

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#220]
Say for example there is a function add(x,y) in   ../models/add/src/func_main.py
What would the serving.yaml look like?

Trying to deploy functions as services(models) to be used in stages within an Application. 

Thanks

**Comment by tidylobster** [comment]
Hi, you can see the examples in the [getting-started](https://hydrosphere.io/serving-docs/getting-started.html#describing-the-model) page. Also, there're a more detailed description of possible values available [here](https://hydrosphere.io/serving-docs/models.html#contracts). For your example it might be something like: 

```yaml
...

contract:
  add:
    inputs:
      x:
        shape: scalar
        type: int32
      y: 
        shape: scalar
        type: int32
    outputs:
      z:
        shape: scalar
        type: int32
```
